### ISSUE TITLE
Blacklist not Enabled

### ISSUE THREAD

**Issue by daheise** [cooperlees/pypistats#3]
According to the docs [here](https://bandersnatch.readthedocs.io/en/latest/filtering_configuration.html) the blacklist configuration need to be of this form:

```[blacklist]
[blacklist]
plugins =
    blacklist_project
packages =
    example1
    ...
```

However, the output of `pypi_stats --bandersnatch-ini` is of this form:
```
[blacklist]
packages =
   example1
   ...
```

In testing, I confirmed that the current output of `pypi_stats --bandersnatch-ini` does not activate blacklist filtering. I will issue a pull request shortly to address this.

**Comment by cooperlees** [comment]
Cool thanks. I was just lazy and didn't think we needed the code to generate that. But the PR will be great. Thanks! :)
