### ISSUE TITLE
pypi.org/stats down 

### ISSUE THREAD

**Issue by jehutyy** [cooperlees/pypistats#5]
The url is not accessible anymore. Is there a workaround or another url to point to ?

**Comment by cooperlees** [comment]
Correct, it is indeed down. It was to heavy on the DB backend, the way it was.

Will try and work on it this week and get it back. There is no workaround.
Follow https://github.com/pypa/warehouse/issues/5769

Will also take PRs to help bring it back.

**Comment by cooperlees** [comment]
Also, out of curiosity, what were you using it for?

**Comment by jehutyy** [comment]
Ok thanks for you reply ; I'm testing bandersnatch and I wanted to use pypistats to generate blacklist according to bandersnatch documentation.

**Comment by cooperlees** [comment]
Ok - stats are back, but the JSON representation 503's - Will see if I can fix it.

https://travis-ci.org/cooperlees/pypistats/jobs/571432785

**Comment by cooperlees** [comment]
https://travis-ci.org/cooperlees/pypistats/builds/571438981

This is all fixed and CI agrees!
